source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FontIcons_Example', :exclusive => true do
  pod 'FontIcons', :path => '../'
end

target 'FontIcons_Tests', :exclusive => true do
  pod 'FontIcons', :path => '../'

  
end
