source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FontIcons_Example' do
  pod 'FontIcons', :path => '../'
end

target 'FontIcons_Tests' do
  pod 'FontIcons', :path => '../'

end
